baseURL = 'https://ashwinbalaji.xyz/'
languageCode = 'en-us'
title = 'Ashwin Balaji'
theme = "poison"
pluralizelisttitles = false

[params]

front_page_content = ["posts", "projects"]

brand = "Ashwin Balaji"                      # name of your site - appears in the sidebar
    # brand_image = "dont_know.png"    # path to the image shown in the sidebar
    description = "Void's Whispers, a Journal of my Distractions and Everything in-between." # Used as default meta description if not specified in front matter
    dark_mode = true                      # optional - defaults to false
    # favicon = "favicon.png"

    github_url = "https://github.com/abalajiksh"
    goodreads_url = "https://instagram.com"
    instagram_url = "https://www.instagram.com/ashwinbalaji00/"
    steam_url= "https://instagram.com"
    strava_url = "https://instagram.com"


menu = [
    {Name = "About", URL = "/about/", HasChildren = false},
    {Name = "Datenschutz", URL = "/datenschutz/", HasChildren = true},
    # {Name = "Projects", URL = "/projects/", HasChildren = false},
    {Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 3},
    ]

[taxonomies]
    series = 'series'
    tags = 'tags'