baseURL = ''
languageCode = 'en-us'
title = 'Ashwin Balaji'
theme = "poison"
paginate = 10
pluralizelisttitles = false

[params]

brand = "Ashwin Balaji"                      # name of your site - appears in the sidebar
    # brand_image = "/images/test.jpg"    # path to the image shown in the sidebar
    description = "Update this description..." # Used as default meta description if not specified in front matter
    dark_mode = true                      # optional - defaults to false
    # favicon = "favicon.png"


menu = [
    {Name = "About", URL = "/about/", HasChildren = false},
    {Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5},

    ]